/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 1ae73db0-4db4-4aa6-8d11-80978848fb9f

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
Proof that the given system of 17 equations in 20 real variables has no solution.

We follow the 5-step proof plan:
1.  Solve the diagonal subsystem in p_k (squared magnitudes) to obtain a parameterization in terms of U=p7 and V=p9.
2.  Extract six cross relations from the off-diagonal equations.
3.  Prove that the complex amplitudes a, b, c, d, e, f are non-zero.
4.  Perform a global phase reduction by defining a unit scalar g such that b' = g*b is real and positive. Show that all primed amplitudes a', ..., f' are real.
5.  Derive three real multiplicative relations from the dot equations and reach an algebraic contradiction.

-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

abbrev v1 (v : Fin 20 → ℝ) := v ⟨0, by decide⟩
abbrev v2 (v : Fin 20 → ℝ) := v ⟨1, by decide⟩
abbrev v3 (v : Fin 20 → ℝ) := v ⟨2, by decide⟩
abbrev v4 (v : Fin 20 → ℝ) := v ⟨3, by decide⟩
abbrev v5 (v : Fin 20 → ℝ) := v ⟨4, by decide⟩
abbrev v6 (v : Fin 20 → ℝ) := v ⟨5, by decide⟩
abbrev v7 (v : Fin 20 → ℝ) := v ⟨6, by decide⟩
abbrev v8 (v : Fin 20 → ℝ) := v ⟨7, by decide⟩
abbrev v9 (v : Fin 20 → ℝ) := v ⟨8, by decide⟩
abbrev v10 (v : Fin 20 → ℝ) := v ⟨9, by decide⟩
abbrev v11 (v : Fin 20 → ℝ) := v ⟨10, by decide⟩
abbrev v12 (v : Fin 20 → ℝ) := v ⟨11, by decide⟩
abbrev v13 (v : Fin 20 → ℝ) := v ⟨12, by decide⟩
abbrev v14 (v : Fin 20 → ℝ) := v ⟨13, by decide⟩
abbrev v15 (v : Fin 20 → ℝ) := v ⟨14, by decide⟩
abbrev v16 (v : Fin 20 → ℝ) := v ⟨15, by decide⟩
abbrev v17 (v : Fin 20 → ℝ) := v ⟨16, by decide⟩
abbrev v18 (v : Fin 20 → ℝ) := v ⟨17, by decide⟩
abbrev v19 (v : Fin 20 → ℝ) := v ⟨18, by decide⟩
abbrev v20 (v : Fin 20 → ℝ) := v ⟨19, by decide⟩

@[simp] lemma v_def (v : Fin 20 → ℝ) (i : Fin 20) : v i = v i := rfl

def p0 (v : Fin 20 → ℝ) := (v1 v)^2 + (v2 v)^2
def p1 (v : Fin 20 → ℝ) := (v3 v)^2 + (v4 v)^2
def p2 (v : Fin 20 → ℝ) := (v5 v)^2 + (v6 v)^2
def p3 (v : Fin 20 → ℝ) := (v7 v)^2 + (v8 v)^2
def p4 (v : Fin 20 → ℝ) := (v9 v)^2 + (v10 v)^2
def p5 (v : Fin 20 → ℝ) := (v11 v)^2 + (v12 v)^2
def p6 (v : Fin 20 → ℝ) := (v13 v)^2 + (v14 v)^2
def p7 (v : Fin 20 → ℝ) := (v15 v)^2 + (v16 v)^2
def p8 (v : Fin 20 → ℝ) := (v17 v)^2 + (v18 v)^2
def p9 (v : Fin 20 → ℝ) := (v19 v)^2 + (v20 v)^2

lemma p0_nonneg (v) : 0 ≤ p0 v := by
  -- Since squares of real numbers are always non-negative, both $v1 v^2$ and $v2 v^2$ are non-negative. Therefore, their sum is also non-negative.
  apply add_nonneg; apply sq_nonneg; apply sq_nonneg
lemma p1_nonneg (v) : 0 ≤ p1 v := by
  -- The square of any real number is non-negative.
  apply add_nonneg; apply sq_nonneg; apply sq_nonneg
lemma p2_nonneg (v) : 0 ≤ p2 v := by
  -- Since squares of real numbers are non-negative, each term in the sum is non-negative.
  apply add_nonneg; apply sq_nonneg; apply sq_nonneg
lemma p3_nonneg (v) : 0 ≤ p3 v := by
  -- The square of any real number is non-negative.
  apply add_nonneg; apply sq_nonneg; apply sq_nonneg
lemma p4_nonneg (v) : 0 ≤ p4 v := by
  -- The square of any real number is non-negative.
  apply add_nonneg; apply sq_nonneg; apply sq_nonneg
lemma p5_nonneg (v) : 0 ≤ p5 v := by
  -- The square of any real number is non-negative.
  apply add_nonneg; apply sq_nonneg; apply sq_nonneg
lemma p6_nonneg (v) : 0 ≤ p6 v := by
  -- The square of any real number is non-negative.
  apply add_nonneg; apply sq_nonneg; apply sq_nonneg
lemma p7_nonneg (v) : 0 ≤ p7 v := by
  -- The square of any real number is non-negative.
  apply add_nonneg; apply sq_nonneg; apply sq_nonneg
lemma p8_nonneg (v) : 0 ≤ p8 v := by
  -- The square of any real number is non-negative.
  apply add_nonneg; apply sq_nonneg; apply sq_nonneg
lemma p9_nonneg (v) : 0 ≤ p9 v := by
  -- The square of any real number is non-negative.
  apply add_nonneg; apply sq_nonneg; apply sq_nonneg

def c0 (v : Fin 20 → ℝ) : ℂ := Complex.mk (v1 v) (v2 v)
def c1 (v : Fin 20 → ℝ) : ℂ := Complex.mk (v3 v) (v4 v)
def c2 (v : Fin 20 → ℝ) : ℂ := Complex.mk (v5 v) (v6 v)
def c3 (v : Fin 20 → ℝ) : ℂ := Complex.mk (v7 v) (v8 v)
def c4 (v : Fin 20 → ℝ) : ℂ := Complex.mk (v9 v) (v10 v)
def c5 (v : Fin 20 → ℝ) : ℂ := Complex.mk (v11 v) (v12 v)
def c6 (v : Fin 20 → ℝ) : ℂ := Complex.mk (v13 v) (v14 v)
def c7 (v : Fin 20 → ℝ) : ℂ := Complex.mk (v15 v) (v16 v)
def c8 (v : Fin 20 → ℝ) : ℂ := Complex.mk (v17 v) (v18 v)
def c9 (v : Fin 20 → ℝ) : ℂ := Complex.mk (v19 v) (v20 v)

def a (v : Fin 20 → ℝ) := c6 v
def b (v : Fin 20 → ℝ) := c9 v
def c (v : Fin 20 → ℝ) := c7 v
def d (v : Fin 20 → ℝ) := c8 v
def e (v : Fin 20 → ℝ) := c4 v
def f (v : Fin 20 → ℝ) := c5 v

@[simp] lemma a_def (v) : a v = c6 v := rfl
@[simp] lemma b_def (v) : b v = c9 v := rfl
@[simp] lemma c_def (v) : c v = c7 v := rfl
@[simp] lemma d_def (v) : d v = c8 v := rfl
@[simp] lemma e_def (v) : e v = c4 v := rfl
@[simp] lemma f_def (v) : f v = c5 v := rfl

@[simp] lemma c0_def (v) : c0 v = Complex.mk (v1 v) (v2 v) := rfl
@[simp] lemma c1_def (v) : c1 v = Complex.mk (v3 v) (v4 v) := rfl
@[simp] lemma c2_def (v) : c2 v = Complex.mk (v5 v) (v6 v) := rfl
@[simp] lemma c3_def (v) : c3 v = Complex.mk (v7 v) (v8 v) := rfl
@[simp] lemma c4_def (v) : c4 v = Complex.mk (v9 v) (v10 v) := rfl
@[simp] lemma c5_def (v) : c5 v = Complex.mk (v11 v) (v12 v) := rfl
@[simp] lemma c6_def (v) : c6 v = Complex.mk (v13 v) (v14 v) := rfl
@[simp] lemma c7_def (v) : c7 v = Complex.mk (v15 v) (v16 v) := rfl
@[simp] lemma c8_def (v) : c8 v = Complex.mk (v17 v) (v18 v) := rfl
@[simp] lemma c9_def (v) : c9 v = Complex.mk (v19 v) (v20 v) := rfl

structure Sys (v : Fin 20 → ℝ) : Prop :=
  (N : p0 v + p1 v + p2 v + p3 v + p4 v + p5 v + p6 v + p7 v + p8 v + p9 v = 1)
  (D1 : p6 v + p7 v + p8 v + p9 v = 1/2)
  (D2 : p4 v + p5 v + p8 v + p9 v = 1/2)
  (D3 : p4 v + p5 v + p6 v + p7 v = 1/2)
  (D4 : p3 v + p5 v + p7 v + p9 v = 1/2)
  (D5 : p2 v + p5 v + p7 v + p9 v = 1/2)
  (D6 : p1 v + p5 v + p7 v + p9 v = 1/2)
  (D7 : p1 v + p2 v + p3 v + p4 v + p6 v + p8 v = 1/2)
  (X1_0 : v13 v * v19 v + v14 v * v20 v + v15 v * v17 v + v16 v * v18 v = 0)
  (X1_2 : v13 v * v20 v - v14 v * v19 v + v15 v * v18 v - v16 v * v17 v = 0)
  (X1_4 : v13 v * v20 v - v14 v * v19 v - v15 v * v18 v + v16 v * v17 v = 0)
  (X2_0 : v11 v * v17 v + v12 v * v18 v + v19 v * v9 v + v20 v * v10 v = 0)
  (X2_1 : v11 v * v18 v - v12 v * v17 v - v19 v * v10 v + v20 v * v9 v = 0)
  (X2_4 : -v11 v * v18 v + v12 v * v17 v - v19 v * v10 v + v20 v * v9 v = 0)
  (X3_0 : v11 v * v13 v + v12 v * v14 v + v15 v * v9 v + v16 v * v10 v = 0)
  (X3_1 : v11 v * v14 v - v12 v * v13 v - v15 v * v10 v + v16 v * v9 v = 0)
  (X3_4 : -v11 v * v14 v + v12 v * v13 v - v15 v * v10 v + v16 v * v9 v = 0)

/-
p2 = p1 and p3 = p1
-/
lemma step1_p123 {v : Fin 20 → ℝ} (h : Sys v) : p2 v = p1 v ∧ p3 v = p1 v := by
  constructor <;> linarith [ h.D4, h.D5, h.D6, h.D7 ]

/-
p6 + p7 = 1/4 and p8 + p9 = 1/4
-/
lemma step1_sums {v : Fin 20 → ℝ} (h : Sys v) : p6 v + p7 v = 1/4 ∧ p8 v + p9 v = 1/4 := by
  constructor <;> linarith! [ h.D1, h.D2, h.D3, h.D4, h.D5, h.D6, h.D7, step1_p123 h ]

/-
p4 + p5 = 1/4
-/
lemma step1_p4p5 {v : Fin 20 → ℝ} (h : Sys v) : p4 v + p5 v = 1/4 := by
  have h_sum : p4 v + p5 v + (p8 v + p9 v) = 1/2 := by
    rw [← add_assoc]
    exact h.D2
  have h_p89 : p8 v + p9 v = 1/4 := (step1_sums h).2
  rw [h_p89] at h_sum
  linarith

/-
p0 + 3 * p1 = 1/4
-/
lemma step1_norm {v : Fin 20 → ℝ} (h : Sys v) : p0 v + 3 * p1 v = 1/4 := by
  obtain ⟨ N, D1, D2, D3, D4, D5, D6, D7, X1_0, X1_2, X1_4, X2_0, X2_1, X2_4, X3_0, X3_1, X3_4 ⟩ := h;
  grind

/-
p1 = 1/16 and p0 = 1/16
-/
lemma step1_solve_t {v : Fin 20 → ℝ} (h : Sys v) : p1 v = 1/16 ∧ p0 v = 1/16 := by
  let S := p4 v + p6 v + p8 v
  have hp5 : p5 v = 1/4 - p4 v := by linarith [step1_p4p5 h]
  have hp7 : p7 v = 1/4 - p6 v := by
    have := (step1_sums h).1
    linarith
  have hp9 : p9 v = 1/4 - p8 v := by
    have := (step1_sums h).2
    linarith
  have ht_eq : p1 v = S - 1/4 := by
    have d6 := h.D6
    rw [hp5, hp7, hp9] at d6
    dsimp [S]
    linarith
  have h_sys : 3 * p1 v + S = 1/2 := by
    have d7 := h.D7
    rw [(step1_p123 h).1, (step1_p123 h).2] at d7
    dsimp [S] at d7 ⊢
    linarith
  have hp1 : p1 v = 1/16 := by linarith
  have hp0 : p0 v = 1/16 := by
    have norm := step1_norm h
    rw [hp1] at norm
    linarith
  constructor
  · exact hp1
  · exact hp0

/-
Full parameterization in terms of p7 and p9
-/
lemma step1_param {v : Fin 20 → ℝ} (h : Sys v) :
  p0 v = 1/16 ∧ p1 v = 1/16 ∧ p2 v = 1/16 ∧ p3 v = 1/16 ∧
  p4 v = p7 v + p9 v - 3/16 ∧ p5 v = 7/16 - p7 v - p9 v ∧
  p6 v = 1/4 - p7 v ∧ p8 v = 1/4 - p9 v := by
  let U := p7 v
  let V := p9 v
  have h_p01 : p1 v = 1/16 ∧ p0 v = 1/16 := step1_solve_t h
  have h_p1 : p1 v = 1/16 := h_p01.1
  have h_p0 : p0 v = 1/16 := h_p01.2
  have h_p2 : p2 v = 1/16 := by rw [(step1_p123 h).1, h_p1]
  have h_p3 : p3 v = 1/16 := by rw [(step1_p123 h).2, h_p1]
  have h_p6 : p6 v = 1/4 - U := by
    have := (step1_sums h).1
    dsimp [U]
    linarith
  have h_p8 : p8 v = 1/4 - V := by
    have := (step1_sums h).2
    dsimp [V]
    linarith
  have h_p5 : p5 v = 7/16 - U - V := by
    have d6 := h.D6
    rw [h_p1] at d6
    dsimp [U, V] at d6 ⊢
    linarith
  have h_p4 : p4 v = U + V - 3/16 := by
    have := step1_p4p5 h
    rw [h_p5] at this
    dsimp [U, V] at this ⊢
    linarith
  refine ⟨h_p0, h_p1, h_p2, h_p3, h_p4, h_p5, h_p6, h_p8⟩

/-
Inequalities for p7 and p9
-/
lemma step1_ineq {v : Fin 20 → ℝ} (h : Sys v) :
  0 ≤ p7 v ∧ p7 v ≤ 1/4 ∧
  0 ≤ p9 v ∧ p9 v ≤ 1/4 ∧
  3/16 ≤ p7 v + p9 v ∧ p7 v + p9 v ≤ 7/16 := by
    -- By definition of $p_k$, we know that $p_k \geq 0$ for all $k$.
    have h_nonneg : 0 ≤ p0 v ∧ 0 ≤ p1 v ∧ 0 ≤ p2 v ∧ 0 ≤ p3 v ∧ 0 ≤ p4 v ∧ 0 ≤ p5 v ∧ 0 ≤ p6 v ∧ 0 ≤ p7 v ∧ 0 ≤ p8 v ∧ 0 ≤ p9 v := by
      exact ⟨ p0_nonneg v, p1_nonneg v, p2_nonneg v, p3_nonneg v, p4_nonneg v, p5_nonneg v, p6_nonneg v, p7_nonneg v, p8_nonneg v, p9_nonneg v ⟩;
    exact ⟨ h_nonneg.2.2.2.2.2.2.2.1, by linarith [ step1_param h ], h_nonneg.2.2.2.2.2.2.2.2.2, by linarith [ step1_param h ], by linarith [ step1_param h ], by linarith [ step1_param h ] ⟩

/-
Cross relations from X1 equations
-/
lemma cross_ba {v : Fin 20 → ℝ} (h : Sys v) : v13 v * v20 v - v14 v * v19 v = 0 := by
  have h_sum : 2 * (v13 v * v20 v - v14 v * v19 v) = 0 := by
    linear_combination h.X1_2 + h.X1_4
  linarith

lemma cross_cd {v : Fin 20 → ℝ} (h : Sys v) : v15 v * v18 v - v16 v * v17 v = 0 := by
  have h_diff : 2 * (v15 v * v18 v - v16 v * v17 v) = 0 := by
    linear_combination h.X1_2 - h.X1_4
  linarith

/-
Remaining cross relations from X2 and X3 equations
-/
lemma cross_be {v : Fin 20 → ℝ} (h : Sys v) : v20 v * v9 v - v19 v * v10 v = 0 := by
  have h_sum : 2 * (v20 v * v9 v - v19 v * v10 v) = 0 := by
    linear_combination h.X2_1 + h.X2_4
  linarith

lemma cross_df {v : Fin 20 → ℝ} (h : Sys v) : v11 v * v18 v - v12 v * v17 v = 0 := by
  have h_diff : 2 * (v11 v * v18 v - v12 v * v17 v) = 0 := by
    linear_combination h.X2_1 - h.X2_4
  linarith

lemma cross_ce {v : Fin 20 → ℝ} (h : Sys v) : v16 v * v9 v - v15 v * v10 v = 0 := by
  have h_sum : 2 * (v16 v * v9 v - v15 v * v10 v) = 0 := by
    linear_combination h.X3_1 + h.X3_4
  linarith

lemma cross_af {v : Fin 20 → ℝ} (h : Sys v) : v11 v * v14 v - v12 v * v13 v = 0 := by
  have h_diff : 2 * (v11 v * v14 v - v12 v * v13 v) = 0 := by
    linear_combination h.X3_1 - h.X3_4
  linarith

/-
b is not zero
-/
lemma step3_b_ne0 {v : Fin 20 → ℝ} (h : Sys v) : b v ≠ 0 := by
  by_contra hb_zero
  have hp9_zero : p9 v = 0 := by
    simp_all +decide [ Complex.ext_iff, p9 ]
  have hp8_one_fourth : p8 v = 1 / 4 := by
    linarith [ h.D3, h.D5, h.D6, h.D7, step1_sums h ]
  have h_conj_d_c_zero : (v15 v * v17 v + v16 v * v18 v = 0) ∧ (v15 v * v18 v - v16 v * v17 v = 0) := by
    have := h.X1_0; ( have := h.X1_2; ( have := h.X1_4; ( have := h.X2_0; ( have := h.X2_1; ( have := h.X2_4; ( have := h.X3_0; ( have := h.X3_1; ( have := h.X3_4; norm_num [ Complex.ext_iff ] at *; aesop; ) ) ) ) ) ) ) )
  have h_c_zero : v15 v = 0 ∧ v16 v = 0 := by
    -- Since $d \neq 0$, we have $v17 v^2 + v18 v^2 \neq 0$.
    have h_d_ne_zero : v17 v^2 + v18 v^2 ≠ 0 := by
      unfold p8 at hp8_one_fourth; linarith;
    grind
  have hp7_zero : p7 v = 0 := by
    unfold p7; aesop;
  have hp4_neg_three_sixteenths : p4 v = -3 / 16 := by
    linarith [ step1_param h ]
  have hp4_nonneg : 0 ≤ p4 v := by
    exact add_nonneg ( sq_nonneg _ ) ( sq_nonneg _ )
  linarith

/-
e is not zero
-/
lemma step3_e_ne0 {v : Fin 20 → ℝ} (h : Sys v) : e v ≠ 0 := by
  by_contra he_zero
  have hp4_zero : p4 v = 0 := by
    unfold e at he_zero; simp_all +decide [ Complex.ext_iff ] ;
    unfold p4; aesop;
  have hp5_one_fourth : p5 v = 1 / 4 := by
    linarith [ step1_param h ]
  have h_conj_fd_zero : (starRingEnd ℂ (f v)) * (d v) = 0 := by
    simp_all +decide [ Complex.ext_iff, p4, p5 ];
    have := h.X2_0; ( have := h.X2_1; ( have := h.X2_4; ( norm_num [ he_zero ] at *; ) ) );
    grind
  have h_f_ne_zero : f v ≠ 0 := by
    unfold f; intro H; simp_all +decide [ Complex.ext_iff ] ;
    unfold p5 at hp5_one_fourth; norm_num [ H, he_zero ] at hp5_one_fourth;
  have h_d_zero : d v = 0 := by
    aesop
  have h_p8_zero : p8 v = 0 := by
    unfold d at h_d_zero; unfold p8; simp_all +decide [ Complex.ext_iff ] ;
  have h_p9_one_fourth : p9 v = 1 / 4 := by
    linarith [ h.D1, h.D2, h.D3, h.D4, h.D5, h.D6, h.D7 ]
  have h_p7_neg : p7 v = 3 / 16 - 1 / 4 := by
    linarith [ step1_param h ]
  have h_p7_neg_contra : (0 : ℝ) ≤ p7 v := by
    exact?
  linarith [h_p7_neg, h_p7_neg_contra]

/-
c is not zero
-/
lemma step3_c_ne0 {v : Fin 20 → ℝ} (h : Sys v) : c v ≠ 0 := by
  by_contra hc_zero
  have h_p7_zero : p7 v = 0 := by
    unfold c p7 at * ; simp_all +decide [ Complex.ext_iff ]
  have h_p6_nonzero : p6 v ≠ 0 := by
    linarith [ step1_sums h ]
  have h_cross_ba_zero : v13 v * v20 v - v14 v * v19 v = 0 := by
    exact?
  have h_cross_cd_zero : v15 v * v18 v - v16 v * v17 v = 0 := by
    exact?
  have h_cross_be_zero : v20 v * v9 v - v19 v * v10 v = 0 := by
    exact?
  have h_cross_df_zero : v11 v * v18 v - v12 v * v17 v = 0 := by
    exact?
  have h_cross_ce_zero : v16 v * v9 v - v15 v * v10 v = 0 := by
    exact?
  have h_cross_af_zero : v11 v * v14 v - v12 v * v13 v = 0 := by
    exact?
  have h_contra : c v = 0 → a v = 0 := by
    intros hc_zero
    have h_conj_b_a_zero : (starRingEnd ℂ (b v)) * a v = 0 := by
      simp_all +decide [ Complex.ext_iff ];
      by_cases h19 : v19 v = 0 <;> by_cases h20 : v20 v = 0 <;> simp_all +decide [ sub_eq_iff_eq_add ];
      · cases h ; aesop;
      · cases h ; aesop;
      · have := h.X1_0; simp_all +decide [ p7 ] ;
        constructor <;> cases lt_or_gt_of_ne h19 <;> cases lt_or_gt_of_ne h20 <;> nlinarith [ mul_self_pos.2 h19, mul_self_pos.2 h20 ];
    exact eq_zero_of_ne_zero_of_mul_left_eq_zero ( by simpa [ Complex.ext_iff ] using step3_b_ne0 h ) h_conj_b_a_zero;
  exact h_p6_nonzero ( by rw [ show p6 v = ( v13 v ) ^ 2 + ( v14 v ) ^ 2 by rfl ] ; exact by rw [ show v13 v = 0 by exact by { have := h_contra hc_zero; simp_all +decide [ Complex.ext_iff ] } ] ; rw [ show v14 v = 0 by exact by { have := h_contra hc_zero; simp_all +decide [ Complex.ext_iff ] } ] ; norm_num )

/-
d is not zero
-/
lemma step3_d_ne0 {v : Fin 20 → ℝ} (h : Sys v) : d v ≠ 0 := by
  by_contra h_contra;
  -- With v17=v18=0, X2-0 becomes v19 v9 + v20 v10 = 0.
  have hX20 : v19 v * v9 v + v20 v * v10 v = 0 := by
    have hX20 : v17 v = 0 ∧ v18 v = 0 := by
      exact ⟨ by simpa using congr_arg Complex.re h_contra, by simpa using congr_arg Complex.im h_contra ⟩;
    have := h.X2_0; aesop;
  -- With Step 2 cross_be: v20 v9 - v19 v10 = 0.
  have hX20_cross : v20 v * v9 v - v19 v * v10 v = 0 := by
    exact?;
  have h_conj_b_e_zero : (c9 v) * starRingEnd ℂ (c4 v) = 0 := by
    exact Complex.ext ( by simpa [ Complex.mul_re ] using by linarith ) ( by simpa [ Complex.mul_im ] using by linarith );
  exact absurd h_conj_b_e_zero ( mul_ne_zero ( step3_b_ne0 h ) ( star_ne_zero.mpr ( step3_e_ne0 h ) ) )

/-
a is not zero
-/
lemma step3_a_ne0 {v : Fin 20 → ℝ} (h : Sys v) : a v ≠ 0 := by
  -- Assume a=0, then p6=0 and by Step 1.6 U=1/4, hence c!=0.
  by_contra h_contra
  have h_p6 : p6 v = 0 := by
    unfold a at h_contra; unfold p6; simp_all +decide [ Complex.ext_iff ] ;
  have h_U : p8 v + p9 v = 1 / 4 := by
    linarith [ step1_sums h ]
  have h_c : c v ≠ 0 := by
    exact?;
  -- With v13=v14=0, X3-0 becomes v15 v9 + v16 v10 = 0.
  have h_X3_0 : v15 v * v9 v + v16 v * v10 v = 0 := by
    have := h.X3_0; simp_all +decide [ Complex.ext_iff ];
  -- With Step 2 cross_ce: v16 v9 - v15 v10 = 0.
  have h_cross_ce : v16 v * v9 v - v15 v * v10 v = 0 := by
    exact?;
  -- These are re/im of conj(e)*c, hence conj(e)*c=0.
  have h_conj_e_c : (v9 v - v10 v * Complex.I) * (v15 v + v16 v * Complex.I) = 0 := by
    simp_all +decide [ Complex.ext_iff ];
    by_cases h15 : v15 v = 0 <;> by_cases h16 : v16 v = 0 <;> simp_all +decide [ sub_eq_iff_eq_add ];
    constructor <;> cases lt_or_gt_of_ne h15 <;> cases lt_or_gt_of_ne h16 <;> nlinarith [ mul_self_pos.2 h15, mul_self_pos.2 h16 ];
  -- Using Step 3.2 e!=0, conclude c=0, contradiction.
  have h_e_ne0 : e v ≠ 0 := by
    exact?;
  simp_all +decide [ Complex.ext_iff ];
  aesop

/-
f is not zero
-/
lemma step3_f_ne0 {v : Fin 20 → ℝ} (h : Sys v) : f v ≠ 0 := by
  cases' h with hN hD1 hD2 hD3 hD4 hD5 hD6 hD7 hX1_0 hX1_2 hX1_4 hX2_0 hX2_1 hX2_4 hX3_0 hX3_1 hX3_4;
  unfold p0 p1 p2 p3 p4 p5 p6 p7 p8 p9 at * ; simp_all +decide ;
  grind

/-
a, b, c, d, e, f are all non-zero
-/
lemma step3_nonzero {v : Fin 20 → ℝ} (h : Sys v) :
  a v ≠ 0 ∧ b v ≠ 0 ∧ c v ≠ 0 ∧ d v ≠ 0 ∧ e v ≠ 0 ∧ f v ≠ 0 := by
  exact ⟨step3_a_ne0 h, step3_b_ne0 h, step3_c_ne0 h, step3_d_ne0 h, step3_e_ne0 h, step3_f_ne0 h⟩

/-
Definition and properties of g using star and norm
-/
noncomputable def g (v : Fin 20 → ℝ) : ℂ := star (b v) / (‖b v‖ : ℂ)

lemma conj_g_mul_g {v : Fin 20 → ℝ} (h : Sys v) : star (g v) * g v = 1 := by
  have h_b_norm : Complex.normSq (b v) ≠ 0 := by
    exact ne_of_gt ( Complex.normSq_pos.mpr ( step3_b_ne0 h ) );
  unfold g; simp_all +decide [Complex.ext_iff] ;
  ring_nf; norm_num [ Complex.normSq, Complex.norm_def, h_b_norm ] ;
  rw [ Real.sq_sqrt ( add_nonneg ( mul_self_nonneg _ ) ( mul_self_nonneg _ ) ) ] ; linear_combination' inv_mul_cancel₀ h_b_norm;

lemma gb_eq_abs {v : Fin 20 → ℝ} (h : Sys v) : g v * b v = (‖b v‖ : ℂ) := by
  unfold g; norm_num [ Complex.ext_iff ] ; ring;
  norm_num [ Complex.normSq, Complex.norm_def ] ; ring;
  rw [ ← add_mul, ← div_eq_mul_inv, Real.div_sqrt ]

#check Real.sqrt
#check Complex.normSq
#check (Complex.normSq (0 : ℂ))

/-
Definition and properties of primed amplitudes
-/
noncomputable def a' (v : Fin 20 → ℝ) := g v * a v
noncomputable def b' (v : Fin 20 → ℝ) := g v * b v
noncomputable def c' (v : Fin 20 → ℝ) := g v * c v
noncomputable def d' (v : Fin 20 → ℝ) := g v * d v
noncomputable def e' (v : Fin 20 → ℝ) := g v * e v
noncomputable def f' (v : Fin 20 → ℝ) := g v * f v

lemma b'_is_real_pos {v : Fin 20 → ℝ} (h : Sys v) : (b' v).im = 0 ∧ 0 < (b' v).re := by
  unfold b';
  rw [ gb_eq_abs ];
  · exact ⟨ by norm_cast, by simpa using norm_pos_iff.mpr ( step3_b_ne0 h ) ⟩;
  · exact h

lemma step4_nonzero {v : Fin 20 → ℝ} (h : Sys v) :
  a' v ≠ 0 ∧ b' v ≠ 0 ∧ c' v ≠ 0 ∧ d' v ≠ 0 ∧ e' v ≠ 0 ∧ f' v ≠ 0 := by
    -- By definition of $a'$, $b'$, etc., we have $a' v = (star (b v) / ‖b v‖) * a v$, $b' v = (star (b v) / ‖b v‖) * b v$, etc.
    simp [a', b', c', d', e', f'];
    simp_all +decide [ Complex.ext_iff, g ];
    have := step3_nonzero h; simp_all +decide [ Complex.ext_iff ] ;

/-
Invariance of conjugate product under multiplication by g
-/
lemma conj_mul_invariant {v : Fin 20 → ℝ} (h : Sys v) (x y : ℂ) :
  star (g v * x) * (g v * y) = star x * y := by
    rw [ mul_comm ];
    simp +zetaDelta at *;
    convert congr_arg ( fun z => z * y * starRingEnd ℂ x ) ( conj_g_mul_g h ) using 1 <;> ring;
    exact?

/-
Invariance of conjugate product under multiplication by g (renamed)
-/
lemma conj_mul_invariant_new {v : Fin 20 → ℝ} (h : Sys v) (x y : ℂ) :
  star (g v * x) * (g v * y) = star x * y := by
    exact?

/-
All primed amplitudes are real
-/
lemma step4_all_real {v : Fin 20 → ℝ} (h : Sys v) :
  (a' v).im = 0 ∧ (b' v).im = 0 ∧ (c' v).im = 0 ∧ (d' v).im = 0 ∧ (e' v).im = 0 ∧ (f' v).im = 0 := by
    -- Use invariance of conjugate product and cross relations to show Im(b'a')=0, Im(b'e')=0, Im(e'c')=0, Im(c'd')=0, Im(d'f')=0.
    have Im_ba_rel : (b' v).im * (a' v).re - (b' v).re * (a' v).im = 0 := by
      have h_cross : star (b' v) * a' v = star (b v) * a v := by
        convert conj_mul_invariant h ( b v ) ( a v ) using 1;
      simp_all +decide [ Complex.ext_iff ];
      linarith [ cross_ba h ]
    have Im_be_rel : (b' v).im * (e' v).re - (b' v).re * (e' v).im = 0 := by
      have := cross_be h; ( have := cross_df h; ( have := cross_ce h; ( have := cross_af h; ( have := b'_is_real_pos h; ( unfold b' e' at *; simp_all +decide ; ) ) ) ) );
      grind +ring
    have Im_ec_rel : (e' v).im * (c' v).re - (e' v).re * (c' v).im = 0 := by
      have := conj_mul_invariant_new h ( e v ) ( c v ) ; simp_all +decide [ Complex.ext_iff ] ;
      unfold e' c'; simp_all +decide ;
      linarith [ step1_param h |>.2.2.2.2.2.2.1, step1_param h |>.2.2.2.2.2.2.2, step1_ineq h, cross_ba h, cross_cd h, cross_be h, cross_df h, cross_ce h, cross_af h ]
    have Im_cd_rel : (c' v).im * (d' v).re - (c' v).re * (d' v).im = 0 := by
      -- Use invariance of conjugate product to show Im(b'a')=0, Im(b'e')=0, Im(e'c')=0, Im(c'd')=0, Im(d'f')=0.
      have h_cross_cd : star (c' v) * d' v = star (c v) * d v := by
        apply conj_mul_invariant_new h (c v) (d v);
      simp_all +decide [ Complex.ext_iff ];
      linarith [ cross_cd h ]
    have Im_df_rel : (d' v).im * (f' v).re - (d' v).re * (f' v).im = 0 := by
      -- Use invariance of conjugate product and cross relations to show Im(d'f')=0.
      have Im_df_rel : star (d' v) * f' v = star (d v) * f v := by
        convert conj_mul_invariant h ( d v ) ( f v ) using 1;
      replace Im_df_rel := congr_arg Complex.im Im_df_rel; simp_all +decide ;
      linarith [ step3_a_ne0 h, step3_b_ne0 h, step3_c_ne0 h, step3_d_ne0 h, step3_e_ne0 h, step3_f_ne0 h, step1_ineq h, step1_p4p5 h, step1_sums h, step1_solve_t h, step1_param h, cross_ba h, cross_cd h, cross_be h, cross_df h, cross_ce h, cross_af h ];
    -- Since b' is real != 0, a' and e' are real.
    have h_a_real : (a' v).im = 0 := by
      have := b'_is_real_pos h; aesop;
    have h_e_real : (e' v).im = 0 := by
      have := b'_is_real_pos h; aesop;
    have h_b_real : (b' v).im = 0 := by
      have := b'_is_real_pos h; aesop;
    have h_c_real : (c' v).im = 0 := by
      -- Since e' is real and non-zero, we can divide both sides of the equation by e' to get c' is real.
      have h_e_nonzero : e' v ≠ 0 := by
        exact step4_nonzero h |>.2.2.2.2.1
      have h_c_real : (c' v).im = 0 := by
        simp_all +decide [ Complex.ext_iff ]
      exact h_c_real
    have h_d_real : (d' v).im = 0 := by
      have := step4_nonzero h; simp_all +decide [ Complex.ext_iff ] ;
    have h_f_real : (f' v).im = 0 := by
      -- Since $d' v$ is real and non-zero, $f' v$ must also be real.
      have h_f_real : (f' v).im = 0 := by
        have h_d_ne_zero : d' v ≠ 0 := by
          exact step4_nonzero h |>.2.2.2.1
        simp_all +decide [ Complex.ext_iff ]
      exact h_f_real
    exact ⟨h_a_real, h_b_real, h_c_real, h_d_real, h_e_real, h_f_real⟩

/-
All primed amplitudes are real (renamed)
-/
lemma step4_primed_real {v : Fin 20 → ℝ} (h : Sys v) :
  (a' v).im = 0 ∧ (b' v).im = 0 ∧ (c' v).im = 0 ∧ (d' v).im = 0 ∧ (e' v).im = 0 ∧ (f' v).im = 0 := by
    exact?

/-
Real multiplicative relations from dot equations
-/
lemma rel1 {v : Fin 20 → ℝ} (h : Sys v) : star (b v) * a v + star (d v) * c v = 0 := by
  unfold a b c d; simp +decide [ Complex.ext_iff ] ; ring;
  constructor <;> linarith! [ h.X1_0, h.X1_2, h.X1_4 ]

lemma rel2 {v : Fin 20 → ℝ} (h : Sys v) : star (b v) * e v + star (d v) * f v = 0 := by
  simp_all +decide [ Complex.ext_iff ];
  constructor <;> linarith! [ h.X2_0, h.X2_1, h.X2_4 ]

lemma rel3 {v : Fin 20 → ℝ} (h : Sys v) : star (f v) * a v + star (e v) * c v = 0 := by
  simp_all +decide [ Complex.ext_iff ];
  constructor <;> linarith [ h.X3_0, h.X3_1, h.X3_4 ]

/-
Primed equations eq1, eq2, eq3
-/
lemma eq1 {v : Fin 20 → ℝ} (h : Sys v) : b' v * a' v = - (d' v * c' v) := by
  have eq1 : star (b' v) * a' v + star (d' v) * c' v = 0 := by
    convert rel1 h using 1;
    convert congr_arg₂ ( · + · ) ( conj_mul_invariant h ( b v ) ( a v ) ) ( conj_mul_invariant h ( d v ) ( c v ) ) using 1;
  -- Since $a'$, $b'$, $c'$, and $d'$ are real, we can remove the conjugates.
  have h_real : (a' v).im = 0 ∧ (b' v).im = 0 ∧ (c' v).im = 0 ∧ (d' v).im = 0 := by
    exact ⟨ step4_primed_real h |>.1, step4_primed_real h |>.2.1, step4_primed_real h |>.2.2.1, step4_primed_real h |>.2.2.2.1 ⟩;
  simp_all +decide [ Complex.ext_iff ];
  linarith

lemma eq2 {v : Fin 20 → ℝ} (h : Sys v) : b' v * e' v = - (d' v * f' v) := by
  -- Using the definition of `b'`, `e'`, `d'`, and `f'`, and the relations obtained by multiplying both sides of `rel2` by `star (g v) * g v`, we obtain the desired equality.
  have eq2' : star (g v * b v) * (g v * e v) = - (star (g v * d v) * (g v * f v)) := by
    have eq2' : star (b v) * e v = - (star (d v) * f v) := by
      exact eq_neg_of_add_eq_zero_left ( rel2 h );
    simp +zetaDelta at *;
    linear_combination' eq2' * starRingEnd ℂ ( g v ) * g v;
  -- Since primed variables are real, their conjugates are themselves.
  have h_conj : star (g v * b v) = g v * b v ∧ star (g v * d v) = g v * d v ∧ star (g v * e v) = g v * e v ∧ star (g v * f v) = g v * f v := by
    have h_conj : ∀ (x : ℂ), (x.im = 0) → star x = x := by
      simp +contextual [ Complex.ext_iff ];
    exact ⟨ h_conj _ ( step4_primed_real h |>.2.1 ), h_conj _ ( step4_primed_real h |>.2.2.2.1 ), h_conj _ ( step4_primed_real h |>.2.2.2.2.1 ), h_conj _ ( step4_primed_real h |>.2.2.2.2.2 ) ⟩;
  aesop

lemma eq3 {v : Fin 20 → ℝ} (h : Sys v) : c' v * e' v = - (a' v * f' v) := by
  -- Apply the equality of conjugates and simplify:
  have h_eq2_simp : star (b v) * e v + star (d v) * f v = 0 := by
    convert rel2 h using 1
  have h_eq3_simp : star (f v) * a v + star (e v) * c v = 0 := by
    exact?
  have h_eq3_simp' : f v * star (a v) + e v * star (c v) = 0 := by
    simpa [ Complex.ext_iff ] using congr_arg Star.star h_eq3_simp
  have h_eq3_simp'' : star (g v * f v) * (g v * a v) + star (g v * e v) * (g v * c v) = 0 := by
    norm_num +zetaDelta at *;
    grind;
  unfold c' e' a' f';
  -- Since the primed variables are real, their conjugates are equal to themselves.
  have h_real : star (g v * f v) = g v * f v ∧ star (g v * e v) = g v * e v ∧ star (g v * a v) = g v * a v ∧ star (g v * c v) = g v * c v := by
    have h_real : (g v * f v).im = 0 ∧ (g v * e v).im = 0 ∧ (g v * a v).im = 0 ∧ (g v * c v).im = 0 := by
      have := step4_primed_real h; aesop;
    simp_all +decide [ Complex.ext_iff ];
    exact ⟨ by linarith, by linarith, by linarith, by linarith ⟩;
  grind

/-
The system has no solution
-/
theorem no_solution : ¬ ∃ v : Fin 20 → ℝ, Sys v := by
  by_contra h_contra
  obtain ⟨v, hv⟩ := h_contra
  have eq1 : b' v * a' v = - (d' v * c' v) := by
    exact?
  have eq2 : b' v * e' v = - (d' v * f' v) := by
    exact?
  have eq3 : c' v * e' v = - (a' v * f' v) := by
    exact?;
  have h_contra : a' v * f' v = -a' v * f' v := by
    have h_contra : b' v ≠ 0 := by
      exact step4_nonzero hv |>.2.1;
    grind;
  have h_contra : a' v * f' v = 0 := by
    linear_combination' h_contra / 2;
  exact absurd h_contra ( mul_ne_zero ( step4_nonzero hv |>.1 ) ( step4_nonzero hv |>.2.2.2.2.2 ) )
