/-
This file was generated by Aristotle (https://aristotle.harmonic.fun).

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 4d9a9624-dce5-451b-a8dd-7d7eefa061bf

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>
-/

/-
We prove that a system of 19 quadratic equations in 28 real variables has no real solution.
The proof proceeds by defining the variables and equations in terms of complex numbers and their norms.
We then prove a series of lemmas (L1-L11) deriving consequences of these equations, including linear relations, multiplicative identities, and bounds on specific quantities T and U.
Finally, we use a gauge transformation argument to show that the derived bounds lead to a contradiction, thus proving that no solution exists.
-/

import Mathlib

set_option linter.mathlibStandardSet false

open scoped BigOperators
open scoped Real
open scoped Nat
open scoped Classical
open scoped Pointwise

set_option maxHeartbeats 0
set_option maxRecDepth 4000
set_option synthInstance.maxHeartbeats 20000
set_option synthInstance.maxSize 128

set_option relaxedAutoImplicit false
set_option autoImplicit false

noncomputable section

/-
Definitions of the 19 equations for the quadratic system.
-/
def p (c : Fin 14 → ℂ) (k : Fin 14) : ℝ := Complex.normSq (c k)

def E1 (c : Fin 14 → ℂ) : Prop :=
  (Finset.univ.sum (fun i => p c i)) = 1

def E2 (c : Fin 14 → ℂ) : Prop :=
  p c 7 + p c 8 + p c 9 + p c 10 + p c 11 + p c 12 + p c 13 = 1/2

def E3 (c : Fin 14 → ℂ) : Prop :=
  p c 5 + p c 6 + p c 12 + p c 13 = 1/2

def E4 (c : Fin 14 → ℂ) : Prop :=
  p c 4 + p c 6 + p c 11 + p c 13 = 1/2

def E5 (c : Fin 14 → ℂ) : Prop :=
  p c 3 + p c 4 + p c 5 + p c 10 + p c 11 + p c 12 = 1/2

def E6 (c : Fin 14 → ℂ) : Prop :=
  p c 2 + p c 3 + p c 6 + p c 9 + p c 10 + p c 13 = 1/2

def E7 (c : Fin 14 → ℂ) : Prop :=
  p c 1 + p c 3 + p c 6 + p c 8 + p c 10 + p c 13 = 1/2

def E8 (c : Fin 14 → ℂ) : Prop :=
  p c 1 + p c 2 + p c 4 + p c 5 + p c 8 + p c 9 + p c 11 + p c 12 = 1/2

def E9 (c : Fin 14 → ℂ) : Prop :=
  (star (c 0) * c 7).im + (star (c 1) * c 8).im +
  (star (c 2) * c 9).im + (star (c 3) * c 10).im +
  (star (c 4) * c 11).im + (star (c 5) * c 12).im +
  (star (c 6) * c 13).im = 0

def E10 (c : Fin 14 → ℂ) : Prop :=
  (star (c 5) * c 13).re + (star (c 6) * c 12).re = 0

def E11 (c : Fin 14 → ℂ) : Prop :=
  (star (c 5) * c 13).im + (star (c 6) * c 12).im = 0

def E12 (c : Fin 14 → ℂ) : Prop :=
  (star (c 5) * c 13).im - (star (c 6) * c 12).im = 0

def E13 (c : Fin 14 → ℂ) : Prop :=
  (star (c 4) * c 13).re + (star (c 6) * c 11).re = 0

def E14 (c : Fin 14 → ℂ) : Prop :=
  (star (c 4) * c 13).im + (star (c 6) * c 11).im = 0

def E15 (c : Fin 14 → ℂ) : Prop :=
  (star (c 4) * c 13).im - (star (c 6) * c 11).im = 0

def E16 (c : Fin 14 → ℂ) : Prop :=
  (star (c 12) * c 13).re + (star (c 5) * c 6).re = 0

def E17 (c : Fin 14 → ℂ) : Prop :=
  (star (c 12) * c 13).re - (star (c 5) * c 6).re = 0

def E18 (c : Fin 14 → ℂ) : Prop :=
  (star (c 11) * c 13).re + (star (c 4) * c 6).re = 0

def E19 (c : Fin 14 → ℂ) : Prop :=
  (star (c 11) * c 13).re - (star (c 4) * c 6).re = 0

/-
Lemma L1: Linear elimination implies pair sums and linear formulas.
-/
theorem L1 (c : Fin 14 → ℂ)
  (h1 : E1 c) (h2 : E2 c) (h3 : E3 c) (h4 : E4 c)
  (h5 : E5 c) (h6 : E6 c) (h7 : E7 c) (h8 : E8 c) :
  p c 0 + p c 7 = 1/16 ∧
  p c 1 + p c 8 = 1/16 ∧
  p c 2 + p c 9 = 1/16 ∧
  p c 3 + p c 10 = 1/8 ∧
  p c 4 + p c 11 = 3/16 ∧
  p c 5 + p c 12 = 3/16 ∧
  p c 6 + p c 13 = 5/16 ∧
  p c 7 = 1/2 - (p c 8 + p c 9 + p c 10 + p c 11 + p c 12 + p c 13) ∧
  p c 0 = (p c 8 + p c 9 + p c 10 + p c 11 + p c 12 + p c 13) - 7/16 := by
  unfold E1 E2 E3 E4 E5 E6 E7 E8 at *; norm_num [ Fin.sum_univ_succ ] at *;
  grind

/-
Lemma L2: The (E10)--(E12) block forces a multiplicative identity.
-/
theorem L2 (c : Fin 14 → ℂ)
  (h10 : E10 c) (h11 : E11 c) (h12 : E12 c) :
  p c 5 * p c 13 = p c 6 * p c 12 := by
  unfold E10 E11 E12 at *;
  unfold p;
  simp_all +decide [Complex.normSq];
  grind +ring

/-
Lemma L3: The (E13)--(E15) block forces a second multiplicative identity.
-/
theorem L3 (c : Fin 14 → ℂ)
  (h13 : E13 c) (h14 : E14 c) (h15 : E15 c) :
  p c 4 * p c 13 = p c 6 * p c 11 := by
  unfold E13 E14 E15 p at *;
  simp_all +decide [Complex.normSq];
  grind

/-
Lemma L4: The multiplicative identities linearize.
-/
theorem L4 (c : Fin 14 → ℂ)
  (h1 : E1 c) (h2 : E2 c) (h3 : E3 c) (h4 : E4 c)
  (h5 : E5 c) (h6 : E6 c) (h7 : E7 c) (h8 : E8 c)
  (h10 : E10 c) (h11 : E11 c) (h12 : E12 c)
  (h13 : E13 c) (h14 : E14 c) (h15 : E15 c) :
  p c 12 = 3/5 * p c 13 ∧
  p c 11 = 3/5 * p c 13 ∧
  p c 5 = 3/5 * p c 6 ∧
  p c 4 = 3/5 * p c 6 := by
  have h_sub : p c 5 = 3 / 16 - p c 12 ∧ p c 6 = 5 / 16 - p c 13 ∧ p c 4 = 3 / 16 - p c 11 := by
    have := L1 c h1 h2 h3 h4 h5 h6 h7 h8;
    exact ⟨ eq_sub_of_add_eq this.2.2.2.2.2.1, eq_sub_of_add_eq this.2.2.2.2.2.2.1, eq_sub_of_add_eq this.2.2.2.2.1 ⟩;
  have h_sub : p c 5 * p c 13 = p c 6 * p c 12 ∧ p c 4 * p c 13 = p c 6 * p c 11 := by
    exact ⟨ L2 c h10 h11 h12, L3 c h13 h14 h15 ⟩;
  grind

/-
Lemma L5: Uniform lower bounds.
-/
theorem L5 (c : Fin 14 → ℂ)
  (h1 : E1 c) (h2 : E2 c) (h3 : E3 c) (h4 : E4 c)
  (h5 : E5 c) (h6 : E6 c) (h7 : E7 c) (h8 : E8 c)
  (h10 : E10 c) (h11 : E11 c) (h12 : E12 c)
  (h13 : E13 c) (h14 : E14 c) (h15 : E15 c) :
  p c 13 ≥ 15/176 ∧ p c 6 ≥ 15/176 := by
  -- From Lemma L4, we have p c 12 = 3/5 * p c 13 and p c 11 = 3/5 * p c 13.
  have hL4 : p c 12 = 3 / 5 * p c 13 ∧ p c 11 = 3 / 5 * p c 13 := by
    exact ⟨ by linarith [ L4 c h1 h2 h3 h4 h5 h6 h7 h8 h10 h11 h12 h13 h14 h15 ], by linarith [ L4 c h1 h2 h3 h4 h5 h6 h7 h8 h10 h11 h12 h13 h14 h15 ] ⟩;
  -- From Lemma L1, we have p c 0 + p c 7 = 1/16 and p c 7 = 1/2 - (p c 8 + p c 9 + p c 10 + p c 11 + p c 12 + p c 13).
  have hL1 : p c 0 + p c 7 = 1 / 16 ∧ p c 7 = 1 / 2 - (p c 8 + p c 9 + p c 10 + p c 11 + p c 12 + p c 13) := by
    exact ⟨ L1 c h1 h2 h3 h4 h5 h6 h7 h8 |>.1, L1 c h1 h2 h3 h4 h5 h6 h7 h8 |>.2.2.2.2.2.2.2.1 ⟩;
  have hL1_bounds : p c 8 ≤ 1 / 16 ∧ p c 9 ≤ 1 / 16 ∧ p c 10 ≤ 1 / 8 := by
    have hL1_bounds : p c 0 + p c 7 = 1 / 16 ∧ p c 1 + p c 8 = 1 / 16 ∧ p c 2 + p c 9 = 1 / 16 ∧ p c 3 + p c 10 = 1 / 8 := by
      exact ⟨ hL1.1, by have := L1 c h1 h2 h3 h4 h5 h6 h7 h8; norm_num at *; linarith, by have := L1 c h1 h2 h3 h4 h5 h6 h7 h8; norm_num at *; linarith, by have := L1 c h1 h2 h3 h4 h5 h6 h7 h8; norm_num at *; linarith ⟩;
    exact ⟨ by linarith [ show 0 ≤ p c 1 from Complex.normSq_nonneg _, show 0 ≤ p c 8 from Complex.normSq_nonneg _ ], by linarith [ show 0 ≤ p c 2 from Complex.normSq_nonneg _, show 0 ≤ p c 9 from Complex.normSq_nonneg _ ], by linarith [ show 0 ≤ p c 3 from Complex.normSq_nonneg _, show 0 ≤ p c 10 from Complex.normSq_nonneg _ ] ⟩;
  -- From Lemma L1, we have p c 6 = 5/16 - p c 13.
  have hL1_p6 : p c 6 = 5 / 16 - p c 13 := by
    linarith [ L1 c h1 h2 h3 h4 h5 h6 h7 h8 ];
  constructor <;> linarith [ show 0 ≤ p c 0 from Complex.normSq_nonneg _, show 0 ≤ p c 7 from Complex.normSq_nonneg _, show 0 ≤ p c 8 from Complex.normSq_nonneg _, show 0 ≤ p c 9 from Complex.normSq_nonneg _, show 0 ≤ p c 10 from Complex.normSq_nonneg _, show 0 ≤ p c 11 from Complex.normSq_nonneg _, show 0 ≤ p c 12 from Complex.normSq_nonneg _, show 0 ≤ p c 13 from Complex.normSq_nonneg _ ]

/-
Lemma L6: Consequences of (E16)--(E19).
-/
theorem L6 (c : Fin 14 → ℂ)
  (h16 : E16 c) (h17 : E17 c) (h18 : E18 c) (h19 : E19 c) :
  (star (c 12) * c 13).re = 0 ∧
  (star (c 5) * c 6).re = 0 ∧
  (star (c 11) * c 13).re = 0 ∧
  (star (c 4) * c 6).re = 0 := by
  unfold E16 E17 E18 E19 at *;
  grind +ring

/-
Lemma L7: Global phase normalization (WLOG).
-/
theorem L7 (c : Fin 14 → ℂ)
  (h1 : E1 c) (h2 : E2 c) (h3 : E3 c) (h4 : E4 c)
  (h5 : E5 c) (h6 : E6 c) (h7 : E7 c) (h8 : E8 c)
  (h10 : E10 c) (h11 : E11 c) (h12 : E12 c)
  (h13 : E13 c) (h14 : E14 c) (h15 : E15 c) :
  let g := star (c 13) / (‖c 13‖ : ℂ)
  let c' := fun k => g * c k
  c' 13 = (‖c 13‖ : ℂ) ∧
  (∀ i j, star (c' i) * c' j = star (c i) * c j) ∧
  (∀ k, p c' k = p c k) := by
  by_cases h : c 13 = 0 <;> simp_all +decide [ div_eq_inv_mul ];
  · have := L5 c h1 h2 h3 h4 h5 h6 h7 h8 h10 h11 h12 h13 h14 h15; simp_all +decide [ p ] ;
    norm_num at this;
  · field_simp [h];
    norm_num [ Complex.ext_iff, sq ];
    field_simp;
    norm_num [ Complex.normSq, Complex.sq_norm ];
    norm_num [ ← sq, p ];
    norm_num [ Complex.normSq_eq_norm_sq, h ]

/-
Lemma L7: Global phase normalization (WLOG).
-/
theorem L7_gauge (c : Fin 14 → ℂ)
  (h1 : E1 c) (h2 : E2 c) (h3 : E3 c) (h4 : E4 c)
  (h5 : E5 c) (h6 : E6 c) (h7 : E7 c) (h8 : E8 c)
  (h10 : E10 c) (h11 : E11 c) (h12 : E12 c)
  (h13 : E13 c) (h14 : E14 c) (h15 : E15 c) :
  let g := star (c 13) / (‖c 13‖ : ℂ)
  let c' := fun k => g * c k
  c' 13 = (‖c 13‖ : ℂ) ∧
  (∀ i j, star (c' i) * c' j = star (c i) * c j) ∧
  (∀ k, p c' k = p c k) := by
  convert L7 c h1 h2 h3 h4 h5 h6 h7 h8 h10 h11 h12 h13 h14 h15 using 1

/-
Lemma L8: Under the gauge c_{13} > 0, several variables are purely real/imaginary.
-/
theorem L8 (c : Fin 14 → ℂ)
  (h1 : E1 c) (h2 : E2 c) (h3 : E3 c) (h4 : E4 c)
  (h5 : E5 c) (h6 : E6 c) (h7 : E7 c) (h8 : E8 c)
  (h10 : E10 c) (h11 : E11 c) (h12 : E12 c)
  (h13 : E13 c) (h14 : E14 c) (h15 : E15 c)
  (h16 : E16 c) (h17 : E17 c) (h18 : E18 c) (h19 : E19 c)
  (h_gauge_im : (c 13).im = 0) (h_gauge_pos : 0 < (c 13).re) :
  (c 4).im = 0 ∧ (c 5).im = 0 ∧
  (c 11).re = 0 ∧ (c 12).re = 0 ∧
  (c 6).re = 0 ∧
  c 4 ≠ 0 ∧ c 5 ≠ 0 ∧ (c 6).im ≠ 0 := by
  -- From (E14) and (E15), get Im(conj(c_4)c_{13})=0. With c_13 real and nonzero this forces Im(c_4)=0.
  have h_im4 : Complex.im (c 4) = 0 := by
    unfold E14 at h14; unfold E15 at h15; simp_all +decide [Complex.mul_im] ;
    nlinarith;
  -- From L6, Re(conj(c_{11})c_{13})=0 and Re(conj(c_{12})c_{13})=0 force Re(c_{11})=Re(c_{12})=0.
  have h_re11 : Complex.re (c 11) = 0 := by
    have := L6 c h16 h17 h18 h19; simp_all +decide ;
    grind +ring
  have h_re12 : Complex.re (c 12) = 0 := by
    have := L6 c h16 h17 h18 h19; simp_all +decide ;
    exact this.1.resolve_right h_gauge_pos.ne'
  have h_re6 : Complex.re (c 6) = 0 := by
    -- From L6, Re(conj(c_4)c_6)=0 and c_4 != 0 (coming from p_4=3/5 p_6 and p_6>0) force Re(c_6)=0.
    have h_re6_zero : (star (c 4) * c 6).re = 0 := by
      linarith! [ L6 c h16 h17 h18 h19 ];
    -- From L4, we know that $p c 4 = 3/5 * p c 6$.
    have h_p4 : p c 4 = 3 / 5 * p c 6 := by
      exact L4 c h1 h2 h3 h4 h5 h6 h7 h8 h10 h11 h12 h13 h14 h15 |>.2.2.2;
    unfold p at h_p4; simp_all +decide [ Complex.normSq ] ;
    cases h_re6_zero <;> simp_all +decide ; nlinarith;
  have h_im5 : Complex.im (c 5) = 0 := by
    simp_all +decide [E10, E11, E12, E13, E14, E15, E16, E17, E18, E19];
    grind
  have h_nonzero4 : c 4 ≠ 0 := by
    intro h; simp_all +decide ;
    have := L4 c h1 h2 h3 h4 h5 h6 h7 h8 h10 h11 h12 h13 h14 h15; simp_all +decide [ p ] ;
    have := L5 c h1 h2 h3 h4 h5 h6 h7 h8 h10 h11 h12 h13 h14 h15; simp_all +decide [ Complex.normSq ] ;
    unfold p at this; simp_all +decide [ Complex.normSq ] ;
    linarith
  have h_nonzero5 : c 5 ≠ 0 := by
    contrapose! h_nonzero4; simp_all +decide [ Complex.ext_iff ] ;
    unfold E1 E2 E3 E4 E5 E6 E7 E8 E10 E11 E12 E13 E14 E15 E16 E17 E18 E19 at * ; simp_all +decide ;
    unfold p at * ; simp_all +decide [Complex.normSq] ;
    grind
  have h_nonzero6 : (c 6).im ≠ 0 := by
    intro h; simp_all +decide [Complex.ext_iff] ;
    unfold E1 E2 E3 E4 E5 E6 E7 E8 E10 E11 E12 E13 E14 E15 E16 E17 E18 E19 at * ; simp_all +decide ;
  exact ⟨h_im4, h_im5, h_re11, h_re12, h_re6, h_nonzero4, h_nonzero5, h_nonzero6⟩

/-
Lemma L9: Define T and compute its absolute value.
-/
theorem L9 (c : Fin 14 → ℂ)
  (h1 : E1 c) (h2 : E2 c) (h3 : E3 c) (h4 : E4 c)
  (h5 : E5 c) (h6 : E6 c) (h7 : E7 c) (h8 : E8 c)
  (h10 : E10 c) (h11 : E11 c) (h12 : E12 c)
  (h13 : E13 c) (h14 : E14 c) (h15 : E15 c)
  (h16 : E16 c) (h17 : E17 c) (h18 : E18 c) (h19 : E19 c)
  (h_gauge_im : (c 13).im = 0) (h_gauge_pos : 0 < (c 13).re) :
  let T := (star (c 4) * c 11).im + (star (c 5) * c 12).im + (star (c 6) * c 13).im
  abs T = 11/5 * Real.sqrt (p c 6 * p c 13) ∧
  abs T ≥ 3/16 := by
  -- After L8, write $c_{11}=i y_{11}$, $c_{12}=i y_{12}$, $c_6=i y_6$ with $y_6 \neq 0$.
  obtain ⟨y11, y12, y6, hy11, hy12, hy6, hy6_ne⟩ : ∃ y11 y12 y6 : ℝ, (c 11).re = 0 ∧ (c 12).re = 0 ∧ (c 11).im = y11 ∧ (c 12).im = y12 ∧ (c 6).re = 0 ∧ (c 6).im = y6 ∧ y6 ≠ 0 := by
    have := L8 c h1 h2 h3 h4 h5 h6 h7 h8 h10 h11 h12 h13 h14 h15 h16 h17 h18 h19 h_gauge_im h_gauge_pos; aesop;
  -- Solve for $y_{11}$, $y_{12}$ from the two real equations and substitute into $T$.
  obtain ⟨y4, y5, hy4, hy5⟩ : ∃ y4 y5 : ℝ, (c 4).re = y4 ∧ (c 4).im = 0 ∧ (c 5).re = y5 ∧ (c 5).im = 0 := by
    unfold E11 E12 E13 E14 E15 at *; norm_num [ Complex.ext_iff ] at *; aesop;
  simp_all +decide;
  -- Substitute the values of $y_{11}$, $y_{12}$, $y_4$, and $y_5$ into $T$.
  have hT_val : y4 * y11 + y5 * y12 + -(y6 * (c 13).re) = (11 / 5) * y6 * (c 13).re ∨ y4 * y11 + y5 * y12 + -(y6 * (c 13).re) = -(11 / 5) * y6 * (c 13).re := by
    unfold E10 E11 E12 E13 E14 E15 E16 E17 E18 E19 at * ; simp_all +decide;
    unfold E1 E2 E3 E4 E5 E6 E7 E8 at * ; simp_all +decide;
    unfold p at *;
    simp_all +decide [ Complex.normSq_apply ];
    grind;
  -- Substitute the values of $y_{11}$, $y_{12}$, $y_4$, and $y_5$ into $|T|$.
  have h_abs_T : |y4 * y11 + y5 * y12 + -(y6 * (c 13).re)| = (11 / 5) * |y6| * (c 13).re := by
    rcases hT_val with h | h <;> rw [ h ] <;> norm_num [ abs_mul, abs_of_pos h_gauge_pos ];
  -- Substitute the values of $p c 6$ and $p c 13$ into the expression for $|T|$.
  have h_p_values : p c 6 = y6^2 ∧ p c 13 = (c 13).re^2 := by
    unfold p; simp +decide [ *, Complex.normSq_apply, sq ] ;
  simp_all +decide;
  rw [ Real.sqrt_mul ( sq_nonneg _ ), Real.sqrt_sq_eq_abs, Real.sqrt_sq h_gauge_pos.le ] ; ring_nf ; norm_num [ h_gauge_pos.le ];
  have := L5 c h1 h2 h3 h4 h5 h6 h7 h8 h10 h11 h12 h13 h14 h15 ; norm_num [ h_p_values ] at this ; nlinarith [ abs_mul_abs_self y6, abs_nonneg y6 ]

/-
Lemma L10: Define U and bound it from above.
-/
theorem L10 (c : Fin 14 → ℂ)
  (h1 : E1 c) (h2 : E2 c) (h3 : E3 c) (h4 : E4 c)
  (h5 : E5 c) (h6 : E6 c) (h7 : E7 c) (h8 : E8 c) :
  let U := (star (c 0) * c 7).im + (star (c 1) * c 8).im + (star (c 2) * c 9).im + (star (c 3) * c 10).im
  abs U ≤ 5/32 := by
  have := L1 c h1 h2 h3 h4 h5 h6 h7 h8;
  -- Apply the inequality $|Im(conj(a)b)| \leq |a||b| \leq (|a|^2 + |b|^2)/2$ to each term in $U$.
  have h_ineq : ∀ i ∈ ({0, 1, 2, 3} : Finset (Fin 14)), abs (Complex.im ((star (c i)) * (c (i + 7)))) ≤ (p c i + p c (i + 7)) / 2 := by
    intros i hi; unfold p; norm_num [ Complex.normSq ] ; ring_nf; norm_num;
    exact abs_le.mpr ⟨ by nlinarith only [ sq_nonneg ( ( c i |> Complex.re ) + ( c ( i + 7 ) |> Complex.im ) ), sq_nonneg ( ( c i |> Complex.im ) - ( c ( i + 7 ) |> Complex.re ) ) ], by nlinarith only [ sq_nonneg ( ( c i |> Complex.re ) - ( c ( i + 7 ) |> Complex.im ) ), sq_nonneg ( ( c i |> Complex.im ) + ( c ( i + 7 ) |> Complex.re ) ) ] ⟩;
  exact abs_le.mpr ⟨ by linarith! [ abs_le.mp ( h_ineq 0 ( by decide ) ), abs_le.mp ( h_ineq 1 ( by decide ) ), abs_le.mp ( h_ineq 2 ( by decide ) ), abs_le.mp ( h_ineq 3 ( by decide ) ) ], by linarith! [ abs_le.mp ( h_ineq 0 ( by decide ) ), abs_le.mp ( h_ineq 1 ( by decide ) ), abs_le.mp ( h_ineq 2 ( by decide ) ), abs_le.mp ( h_ineq 3 ( by decide ) ) ] ⟩

/-
Lemma L11: The Y1 equation ties T and U.
-/
theorem L11 (c : Fin 14 → ℂ)
  (h9 : E9 c) :
  let T := (star (c 4) * c 11).im + (star (c 5) * c 12).im + (star (c 6) * c 13).im
  let U := (star (c 0) * c 7).im + (star (c 1) * c 8).im + (star (c 2) * c 9).im + (star (c 3) * c 10).im
  U + T = 0 ∧ abs T = abs U := by
  unfold E9 at h9;
  exact ⟨ by linarith, by rw [ ← abs_neg ] ; congr; linarith ⟩

/-
Mapping from 28 real variables to 14 complex variables.
-/
def c_from_v (v : Fin 28 → ℝ) : Fin 14 → ℂ :=
  fun k => ⟨v ⟨2 * k.val, by
    fin_cases k <;> decide⟩, v ⟨2 * k.val + 1, by
    decide +revert⟩⟩

/-
Theorem: There does not exist (v_1,...,v_{28}) in R^{28} satisfying (E1)--(E19).
-/
theorem NoRealSolution : ¬ ∃ v : Fin 28 → ℝ,
  let c := c_from_v v
  E1 c ∧ E2 c ∧ E3 c ∧ E4 c ∧ E5 c ∧ E6 c ∧ E7 c ∧ E8 c ∧
  E9 c ∧ E10 c ∧ E11 c ∧ E12 c ∧ E13 c ∧ E14 c ∧ E15 c ∧
  E16 c ∧ E17 c ∧ E18 c ∧ E19 c := by
  by_contra h
  obtain ⟨v, hc⟩ := h
  set c := c_from_v v
  have h_gauge : ∃ g : ℂ, ‖g‖ = 1 ∧ (g * c 13).im = 0 ∧ 0 < (g * c 13).re := by
    use star (c 13) / ‖c 13‖
    generalize_proofs at *;
    by_cases h : c 13 = 0 <;> simp_all +decide [ div_mul_eq_mul_div ];
    · have := L5 c hc.1 hc.2.1 hc.2.2.1 hc.2.2.2.1 hc.2.2.2.2.1 hc.2.2.2.2.2.1 hc.2.2.2.2.2.2.1 hc.2.2.2.2.2.2.2.1 hc.2.2.2.2.2.2.2.2.2.1 hc.2.2.2.2.2.2.2.2.2.2.1 hc.2.2.2.2.2.2.2.2.2.2.2.1 hc.2.2.2.2.2.2.2.2.2.2.2.2.1 hc.2.2.2.2.2.2.2.2.2.2.2.2.2.1 hc.2.2.2.2.2.2.2.2.2.2.2.2.2.2.1 ; simp_all +decide [ Complex.ext_iff, p ] ;
      norm_num [ Complex.normSq, h ] at this;
    · exact ⟨ by ring, by exact not_le.mp fun h' => h <| by refine' Complex.ext _ _ <;> norm_num <;> nlinarith ⟩
  generalize_proofs at *;
  obtain ⟨ g, hg₁, hg₂, hg₃ ⟩ := h_gauge
  have hc_gauge : let c' := fun k => g * c k;
    E1 c' ∧ E2 c' ∧ E3 c' ∧ E4 c' ∧ E5 c' ∧ E6 c' ∧ E7 c' ∧ E8 c' ∧ E9 c' ∧ E10 c' ∧ E11 c' ∧ E12 c' ∧ E13 c' ∧ E14 c' ∧ E15 c' ∧ E16 c' ∧ E17 c' ∧ E18 c' ∧ E19 c' := by
      simp_all +decide [ Complex.normSq, Complex.norm_def ];
      unfold E1 E2 E3 E4 E5 E6 E7 E8 E9 E10 E11 E12 E13 E14 E15 E16 E17 E18 E19 at *;
      -- Since $g$ is a complex number with norm 1, multiplying by $g$ and its conjugate preserves the equations.
      have h_gauge_eq : ∀ i j, star (g * c i) * (g * c j) = star (c i) * c j := by
        simp +decide [Complex.ext_iff, mul_assoc, mul_comm];
        grind +ring
      generalize_proofs at *; (
      simp_all +decide [ p ];
      simp_all +decide [Complex.normSq])
  generalize_proofs at *;
  obtain ⟨ hc₁, hc₂, hc₃, hc₄, hc₅, hc₆, hc₇, hc₈, hc₉, hc₁₀, hc₁₁, hc₁₂, hc₁₃, hc₁₄, hc₁₅, hc₁₆, hc₁₇, hc₁₈, hc₁₉ ⟩ := hc_gauge;
  have := L9 ( fun k => g * c k ) hc₁ hc₂ hc₃ hc₄ hc₅ hc₆ hc₇ hc₈ hc₁₀ hc₁₁ hc₁₂ hc₁₃ hc₁₄ hc₁₅ hc₁₆ hc₁₇ hc₁₈ hc₁₉ hg₂ hg₃; norm_num at this; ( have := L10 ( fun k => g * c k ) hc₁ hc₂ hc₃ hc₄ hc₅ hc₆ hc₇ hc₈; norm_num at this; );
  have := L11 ( fun k => g * c k ) hc₉; norm_num at this; linarith;
